/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2019-01-10 19:59:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Admin;

public final class Add_005fFaculty_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Admin");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<script>\r\n");
      out.write("function Sam()\r\n");
      out.write("{\r\n");
      out.write("\tvar aa=document.getElementById(\"button1\");\r\n");
      out.write("\tif(aa.type==\"password\")\r\n");
      out.write("\t{\r\n");
      out.write("\t  \taa.type=\"text\";\r\n");
      out.write("\t}else{\r\n");
      out.write("\t \taa.type=\"password\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function checkForm(form)\r\n");
      out.write("{\r\n");
      out.write("  if(form.name.value == \"\") \r\n");
      out.write("  {\r\n");
      out.write("    alert(\"Error: Name cannot be blank!\");\r\n");
      out.write("    form.name.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  re =/^[a-z]+$/i;\r\n");
      out.write("  if(!re.test(form.name.value)) \r\n");
      out.write("  {\r\n");
      out.write("    alert(\"Error:Name must contain only letters!\");\r\n");
      out.write("    form.name.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  if(form.uid.value == \"\") \r\n");
      out.write("  {\r\n");
      out.write("    alert(\"Error: User-ID cannot be blank!\");\r\n");
      out.write("    form.uid.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  re = /^\\w+$/;\r\n");
      out.write("  if(!re.test(form.uid.value)) \r\n");
      out.write("  {\r\n");
      out.write("    alert(\"Error: User-ID must contain only letters, numbers and underscores!\");\r\n");
      out.write("    form.uid.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  if(form.cno.value==\"\")\r\n");
      out.write("  {\r\n");
      out.write("\t  alert(\"Error: Contact no. cannot be blank!\");\r\n");
      out.write("\t    form.cno.focus();\r\n");
      out.write("\t    return false;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  if(form.cno.value!=\"\")\r\n");
      out.write("  {\r\n");
      out.write("\t  if(form.cno.value.length !=10) \r\n");
      out.write("\t  {\r\n");
      out.write("\t      alert(\"Error: Enter a valid 10 digit contact no.!\");\r\n");
      out.write("\t      form.cno.focus();\r\n");
      out.write("\t      return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  if(form.eid.value==\"\")\r\n");
      out.write("  {\r\n");
      out.write("\t  alert(\"Error: Email id cannot be blank!\");\r\n");
      out.write("\t    form.eid.focus();\r\n");
      out.write("\t    return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(form.pass.value != \"\" && form.pass.value == form.repass.value) \r\n");
      out.write("  {\r\n");
      out.write("    if(form.pass.value.length < 6) \r\n");
      out.write("    {\r\n");
      out.write("      alert(\"Error: Password must contain at least six characters!\");\r\n");
      out.write("      form.pass.focus();\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    re = /[0-9]/;\r\n");
      out.write("    if(!re.test(form.pass.value)) \r\n");
      out.write("    {\r\n");
      out.write("      alert(\"Error: password must contain at least one number (0-9)!\");\r\n");
      out.write("      form.pass.focus();\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    re = /[a-z]/;\r\n");
      out.write("    if(!re.test(form.pass.value)) \r\n");
      out.write("    {\r\n");
      out.write("      alert(\"Error: password must contain at least one lowercase letter (a-z)!\");\r\n");
      out.write("      form.pass.focus();\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  } \r\n");
      out.write("  else \r\n");
      out.write("  {\r\n");
      out.write("    alert(\"Error: Please check that you've entered and confirmed your password!\");\r\n");
      out.write("    form.pass.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title> ADMIN | ADD_FACULTY </title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tbackground-image:url(2.jpg);\r\n");
      out.write("\tbackground-repeat:no-repeat;\r\n");
      out.write("\t font-family:sans-serif;\r\n");
      out.write("\tbackground-size:100% 920px;\r\n");
      out.write("}\r\n");
      out.write("#MyClockDisplay{\r\n");
      out.write("\tfont-color:red;\r\n");
      out.write("\tfont-style:oblique;\r\n");
      out.write("\tfont-size:15px;\r\n");
      out.write("\tz-index:2;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop:0.5%;\r\n");
      out.write("\tleft:79.5%;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth:100% 900px;\r\n");
      out.write("\tbackground-color:lime;\r\n");
      out.write("\topacity:0.8;\r\n");
      out.write("\tpadding:15px 0px;\r\n");
      out.write("}\r\n");
      out.write("p{\r\n");
      out.write("\twidth:100% 900px;\r\n");
      out.write("\topacity: 0.9;\r\n");
      out.write("\tpadding:0px 0px;\r\n");
      out.write("}\r\n");
      out.write(".vclass-form{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin:30px 460px;\r\n");
      out.write("}\r\n");
      out.write("#registration{\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\tbackground-color:aqua;\r\n");
      out.write("\tborder-radius:10px;\r\n");
      out.write("\topacity:0.9;\r\n");
      out.write("\tpadding:15px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#button{\r\n");
      out.write("\twidth:250px;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tborder-radius:5px;\r\n");
      out.write("\toutline:0px;\t\r\n");
      out.write("}\r\n");
      out.write("#button:hover{\r\n");
      out.write("    cursor: text;\r\n");
      out.write("    background-color: beige;\r\n");
      out.write("    color:#0000a0;\r\n");
      out.write("}\r\n");
      out.write("#button1{\r\n");
      out.write("\twidth:250px;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tborder-radius:5px;\r\n");
      out.write("\toutline:0px;\t\r\n");
      out.write("}\r\n");
      out.write("#button1:hover{\r\n");
      out.write("    cursor: text;\r\n");
      out.write("    background-color: beige;\r\n");
      out.write("    color:#0000a0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#butt{\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\toutline:0px;\r\n");
      out.write("\tbackground-color:black;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("}\r\n");
      out.write(".bank-form:hover{\r\n");
      out.write("    cursor: auto;\r\n");
      out.write("    background-color: beige;\r\n");
      out.write("    color:#0000a0;\r\n");
      out.write("}\r\n");
      out.write(".menu1 nav{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop:86.5%;\r\n");
      out.write("\t\tleft:47%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul{\r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t\tpadding: 0px;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li {\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth: 70px;\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\tborder:1px  solid white;\r\n");
      out.write("\t\topacity: .8;\r\n");
      out.write("\t\tline-height: 15px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 17px;\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\tborder-radius:3px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li.home{\r\n");
      out.write("\t\tbackground-color: dodgerblue;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li a {\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
Admin currentAdmin=(Admin)session.getAttribute("currentAdmin");
	if ( currentAdmin == null) 
    {
 	   response.sendRedirect("Admin_login1.jsp?error=Please Login First !!");
    }
    else{
      out.write("\r\n");
      out.write("<div id=\"MyClockDisplay\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction showTime()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//Date\r\n");
      out.write("\t\t\tvar mydate=new Date();\r\n");
      out.write("\t\t\tvar year=mydate.getYear(); //get the year.\r\n");
      out.write("\t\t\t\tif(year <1000)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tyear+=1900;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\tvar day=mydate.getDay(); //get the day.\r\n");
      out.write("\t\t\tvar month=mydate.getMonth(); //get the month.\r\n");
      out.write("\t\t\tvar daym=mydate.getDate(); //day of the month.\r\n");
      out.write("\t\t\tvar dayarray= new Array(\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\");\r\n");
      out.write("\t\t\tvar montharray=new Array(\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//Time\r\n");
      out.write("\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\tvar h= date.getHours(); //0-23\r\n");
      out.write("\t\t\tvar m= date.getMinutes(); //0-59\r\n");
      out.write("\t\t\tvar s=date.getSeconds(); //0-59\r\n");
      out.write("\t\t\tvar session=\"AM\";\r\n");
      out.write("\t\t\tif(h==0){\r\n");
      out.write("\t\t\t\th=12;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(h>12){\r\n");
      out.write("\t\t\t\th=h-12;\r\n");
      out.write("\t\t\t\tsession=\"PM\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\th=(h<10) ? \"0\"+ h : h;\r\n");
      out.write("\t\t\tm=(m<10) ? \"0\"+ m : m;\r\n");
      out.write("\t\t\ts=(s<10) ? \"0\"+ s : s;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar date1=\"\" +dayarray[day]+ \" \" +daym+ \" \" +montharray[month]+ \" \" +year+   \"  |  \"   +h + \":\" + m + \":\" + s + \" \" + session;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"MyClockDisplay\").innerText = date1;\r\n");
      out.write("\t\t\tdocument.getElementById(\"MyClockDisplay\").textContent = date1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsetTimeout(showTime,1000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tshowTime();\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("<center>\r\n");
      out.write("<font color=\"blue\" size=\"3\">\r\n");
      out.write("<h1><b>VIRTUAL-CLASSROOM</b></h1>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"vclass-form\">\r\n");
      out.write("\r\n");
      out.write("<form action=\"add_faculty\" id=\"registration\" method=\"post\" onsubmit=\"return checkForm(this);\">\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<h2 align=\"center\"><b>ADD FACULTY</b></h2>\r\n");
      out.write("<tr><td align=\"center\">NAME</td><td align=\"center\"><input type=\"text\" name=\"name\" title=\"Name must not be blank and contain only letters.\" id=\"button\" placeholder=\"Enter the Faculty name\"></td></tr>\r\n");
      out.write("<tr><td align=\"center\">USER-ID</td><td align=\"center\"><input type=\"text\" name=\"uid\" title=\"User-ID must not be blank and contain only letters, numbers and underscores.\" id=\"button\" placeholder=\"Enter the User-ID\"></td></tr>\r\n");
      out.write("<tr><td align=\"center\">CONTACT NO.</td><td align=\"center\"><input type=\"number\" name=\"cno\" title=\"Contact no. must be of 10 digits\" id=\"button\" placeholder=\"Enter the contact no.\"></td></tr>\r\n");
      out.write("<tr><td align=\"center\">EMAIL-ID</td><td align=\"center\"><input type=\"email\" name=\"eid\" title=\"Email id must be a valid one\" id=\"button\" placeholder=\"Enter the email-id\"></td></tr>\r\n");
      out.write("<tr><td align=\"center\">PASSWORD</td><td align=\"center\"><input type=\"password\" name=\"pass\" title=\"Password must contain at least 6 characters, including UPPER/lowercase and numbers.\" id=\"button1\" placeholder=\"Enter the password\"></td><td><input type=\"checkbox\" onclick=\"return Sam();\">Show password</td></tr>\r\n");
      out.write("<tr><td align=\"center\">CONFIRM PASSWORD</td><td align=\"center\"><input type=\"password\" name=\"repass\" title=\"Please enter the same Password as above.\" id=\"button\" placeholder=\"Re-Enter the password\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<input type=\"submit\" value=\"ADD\" id=\"butt\">&nbsp\r\n");
      out.write("<input type=\"reset\" value=\"RESET\" id=\"butt\">\r\n");
      out.write("<br><br>\r\n");
      out.write("</form>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"menu1\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"home\"><a href=\"Admin_logged.jsp\"><br><i class=\"fa fa-home\" aria-hidden=\"true\"></i><br>Home</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</font>\r\n");
      out.write("</center>\r\n");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
