/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2019-01-10 19:53:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Faculty;
import model.Admin;
import java.util.List;

public final class display_005ffaculty_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Faculty");
    _jspx_imports_classes.add("model.Admin");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title> ADMIN | VIEW_FACULTY </title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<style type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground-image:url(pic1.jpg);\r\n");
      out.write("\t\tbackground-repeat:no-repeat;\r\n");
      out.write("\t \tfont-family:sans-serif;\r\n");
      out.write("\t\tbackground-size:cover;\r\n");
      out.write("\t}\r\n");
      out.write("\t#MyClockDisplay{\r\n");
      out.write("\t\tfont-color:red;\r\n");
      out.write("\t\tfont-style:oblique;\r\n");
      out.write("\t\tfont-size:17px;\r\n");
      out.write("\t\tz-index:2;\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop:94.5%;\r\n");
      out.write("\t\tleft:78%;\r\n");
      out.write("\t}\r\n");
      out.write("\th2{\r\n");
      out.write("\t\tcolor:#800000;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel h2{\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.menu nav{\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu nav ul{\r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t\tpadding: 0px;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu nav ul li {\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tborder:1px  solid white;\r\n");
      out.write("\t\topacity: .8;\r\n");
      out.write("\t\tline-height: 40px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\tborder-radius:3px;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu nav ul li a {\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu nav ul li a:hover {\r\n");
      out.write("\t\tbackground-color: green;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu nav ul ul  {\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu nav ul li:hover > ul {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu nav ul ul ul{\r\n");
      out.write("\t\tmargin-left: 200px;\r\n");
      out.write("\t\ttop:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop:82%;\r\n");
      out.write("\t\tleft:38%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul{\r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t\tpadding: 0px;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li {\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth: 120px;\r\n");
      out.write("\t\theight: 70px;\r\n");
      out.write("\t\tborder:1px  solid white;\r\n");
      out.write("\t\topacity: .8;\r\n");
      out.write("\t\tline-height: 15px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 17px;\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\tborder-radius:3px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li.home{\r\n");
      out.write("\t\tbackground-color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li.profile{\r\n");
      out.write("\t\tbackground-color: #00ff00;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li.add{\r\n");
      out.write("\t\tbackground-color:#ff0080;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu1 nav ul li a {\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"MyClockDisplay\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction showTime()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//Date\r\n");
      out.write("\t\t\tvar mydate=new Date();\r\n");
      out.write("\t\t\tvar year=mydate.getYear(); //get the year.\r\n");
      out.write("\t\t\t\tif(year <1000)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tyear+=1900;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\tvar day=mydate.getDay(); //get the day.\r\n");
      out.write("\t\t\tvar month=mydate.getMonth(); //get the month.\r\n");
      out.write("\t\t\tvar daym=mydate.getDate(); //day of the month.\r\n");
      out.write("\t\t\tvar dayarray= new Array(\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\");\r\n");
      out.write("\t\t\tvar montharray=new Array(\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//Time\r\n");
      out.write("\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\tvar h= date.getHours(); //0-23\r\n");
      out.write("\t\t\tvar m= date.getMinutes(); //0-59\r\n");
      out.write("\t\t\tvar s=date.getSeconds(); //0-59\r\n");
      out.write("\t\t\tvar session=\"AM\";\r\n");
      out.write("\t\t\tif(h==0){\r\n");
      out.write("\t\t\t\th=12;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(h>12){\r\n");
      out.write("\t\t\t\th=h-12;\r\n");
      out.write("\t\t\t\tsession=\"PM\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\th=(h<10) ? \"0\"+ h : h;\r\n");
      out.write("\t\t\tm=(m<10) ? \"0\"+ m : m;\r\n");
      out.write("\t\t\ts=(s<10) ? \"0\"+ s : s;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar date1=\"\" +dayarray[day]+ \" \" +daym+ \" \" +montharray[month]+ \" \" +year+   \"  |  \"   +h + \":\" + m + \":\" + s + \" \" + session;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"MyClockDisplay\").innerText = date1;\r\n");
      out.write("\t\t\tdocument.getElementById(\"MyClockDisplay\").textContent = date1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsetTimeout(showTime,1000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tshowTime();\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"menu\">\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"Admin_logged.jsp\">Home</a></li>\r\n");
      out.write("\t\t<li><a>Profile</a>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"adm_pro\">View Profile</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li><a href=\"Add_Faculty.jsp\">Add Faculty</a></li>\r\n");
      out.write("\t\t<li><a href=\"display_faculty\">View Faculty</a></li>\r\n");
      out.write("\t\t<li><a href=\"LogoutServlet1\">Logout</a></li>\t\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
Admin currentAdmin=(Admin)session.getAttribute("currentAdmin");
      out.write("\r\n");
      out.write("\t<h2>Welcome to Virtual Classroom</h2>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<center>\r\n");
      out.write("     <div class=\"panel\">\r\n");
      out.write("            <h2>Faculty List</h2>\r\n");
      out.write("            <table class=\"bordered_table\" align=center border=\"3\" width=\"1000px\" >\r\n");
      out.write("               <thead>\r\n");
      out.write("                  <tr align=\"center\"><th>Faculty Name</th><th>User-ID</th><th>Contact No.</th><th>Email-ID</th><th colspan=2>Action</th></tr>\r\n");
      out.write("               </thead>\r\n");
      out.write("               <tbody>\r\n");
      out.write("                  ");
 List<Faculty> facultyList = (List<Faculty>)request.getAttribute("facultyList");
                     if(facultyList != null && facultyList.size() > 0) 
                     {
							for(int i=0; i<facultyList.size(); i++) 
							{
                   
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td align=\"center\"><span id=\"facultyName\">");
      out.print(facultyList.get(i).getName() );
      out.write("</span></td>\r\n");
      out.write("                     <td align=\"center\"><span id=\"user-id\">");
      out.print(facultyList.get(i).getUser_id() );
      out.write("</span></td>\r\n");
      out.write("                     <td align=\"center\"><span id=\"phno\">");
      out.print(facultyList.get(i).getPhno() );
      out.write("</span></td>\r\n");
      out.write("                     <td align=\"center\"><span id=\"email_id\">");
      out.print(facultyList.get(i).getEid() );
      out.write("</span></td>\r\n");
      out.write("                     <td align=\"center\"><span id=\"remove\"><a id=\"removalLink\" class=\"hyperLink\" href=\"remove?facultyName=");
      out.print(facultyList.get(i).getName());
      out.write("&user-id=");
      out.print(facultyList.get(i).getUser_id() );
      out.write("\">Remove</a></span></td>\r\n");
      out.write("                     <td align=\"center\"><span id=\"edit\"><a id=\"editLink\" class=\"hyperLink\" href=\"edit?facultyName=");
      out.print(facultyList.get(i).getName());
      out.write("&user-id=");
      out.print(facultyList.get(i).getUser_id() );
      out.write("\">Edit</a></span></td>\r\n");
      out.write("                 \r\n");
      out.write("                  </tr>\r\n");
      out.write("                  ");
 }
                   } else { 
      out.write("\r\n");
      out.write("                  <tr>\r\n");
      out.write("\r\n");
      out.write("                     <td colspan=\"3\" align=\"center\"><span id=\"noFiles\">No Faculty.....!</span></td>\r\n");
      out.write("\r\n");
      out.write("                  </tr>\r\n");
      out.write("\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </tbody>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         </center>\r\n");
      out.write("         <div class=\"menu1\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"home\"><a href=\"Admin_logged.jsp\"><br><i class=\"fa fa-home\" aria-hidden=\"true\"></i><br>Home</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"profile\"><a href=\"adm_pro\"><br><i class=\"fa fa-user\" aria-hidden=\"true\"></i><br>View Profile</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"add\"><a href=\"Add_Faculty.jsp\"><br><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i><br>Add Faculty</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
